Feature/api
MrCellophane/TaskManager pull request #22
Opened 2019-12-17 14:15 UTC by MrCellophane

2019-12-17 20:24 UTC, Andrew8xx8 requested changes

2019-12-17 20:24 UTC, Andrew8xx8 commented on app/controllers/api/v1/application_controller.rb
> +  helper_method :current_user
Что делает helper_method? Разве он нужен в API?

2019-12-17 21:46 UTC, pn-y requested changes

2019-12-17 21:46 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    if task.save
Экшоном выше ты используешь `respond_with`.
Сможешь ли ты использовать его и здесь?

2019-12-17 21:46 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    if task.update(task_params)
и здесь

2019-12-17 21:46 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    if task.destroy
ну ты понел

2019-12-17 21:46 UTC, pn-y commented on app/models/user.rb
> +  def name
Вспомни доклад про слоистую архитектуру.
`name` - это слой представления, а не модели

2019-12-17 21:46 UTC, pn-y commented on app/serializers/task_serializer.rb
> +    object.id.to_s
Почему цифровой ID сериализуется в строку7

2019-12-17 21:46 UTC, pn-y commented on app/views/admin/users/_form.html.slim
> +      = f.button :submit, "Back", formaction: admin_users_url, formmethod: "get"
Если ты хочешь просто сделать ссылку назад - тебе нужен link_to для того чтоб сделать простую ссылку. Когда тебе приходится костылить - скорее всего что-то происходит не так.

2019-12-17 21:46 UTC, pn-y commented on app/views/admin/users/edit.html.slim
> += simple_form_for [:admin, @user], as: :user, url: admin_user_url do |f|
url как и имя модели можно не указывать, все должно продолжить работать и без этого.

2019-12-17 21:46 UTC, pn-y commented on app/views/admin/users/new.html.slim
> += simple_form_for @user, url: new_admin_user_path do |f|
кажется здесь потерян скоуп admin

2019-12-17 21:46 UTC, pn-y commented on app/views/admin/users/new.html.slim
> +  = f.button :submit, "Create", formaction: admin_users_path
поэтому здесь пришлось написать роут руками

2019-12-17 21:46 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_response :redirect
Тест должен нести практический смысл. 
Если ты вызываешь create - то ожидаемое поведение это создание новой сущности в первую очередь, а не просто редирект.

2019-12-17 21:46 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_response :redirect
и тут

2019-12-17 21:46 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_response :redirect
и тут

2019-12-17 21:46 UTC, pn-y commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
Тест упадет на 28 строке , если что-то пойдет не так. Поэтому эта проверка совсем не обязательна.
Мне кажется канонично проверять `assert Task.exists?(id: id)`, если оно надо

2019-12-24 09:08 UTC, pn-y approved these changes

2019-12-24 09:11 UTC, pn-y requested changes

2019-12-24 09:11 UTC, pn-y commented on app/models/user_staf.rb
> +  def name
Так штуки в рельсе не принято делать.

2019-12-24 09:11 UTC, pn-y commented on app/models/user.rb
> +  include UserStaf
То что ты вынесла функцию в отдельный модуль и заинклудила в модель - не значит что она больше не в модели. Этого в принципе не должно быть в модели. Это другой слой. Это хелпер/презентер/сериалайзер/функция_где_нибудь_но_не_в_модели_точно

2019-12-24 09:11 UTC, pn-y commented on app/serializers/task_serializer.rb
> +  def id
Этот метод не нужен. Можно удалить совсем.

2019-12-24 09:14 UTC, Andrew8xx8 requested changes

2019-12-24 09:14 UTC, Andrew8xx8 commented on app/controllers/admin/users_controller.rb
> +class Admin::UsersController < Admin::ApplicationController
этот файл уже должен быть замержен в предыдущей задаче, почему он здесь?

2019-12-24 09:31 UTC, MrCellophane commented on app/controllers/admin/users_controller.rb
> +class Admin::UsersController < Admin::ApplicationController
все замержено, но пришлось редактировать уже в этой ветке предыдущие тесты

2019-12-25 10:39 UTC, closed without merging